/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.demodragon.gui;

import autonoma.demodragon.elements.Cueva;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.util.HashSet;

/**
 *
 * @author Heily Yohana Rios Ayala <heilyy.riosa@autonoma.edu.co>
 */
public class GameDragon extends javax.swing.JFrame {

    private Cueva cueva;
    
    /**
     * Creates new form GameWindow
     */
    public GameDragon() {
        initComponents();
        this.setSize(900,700);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
   switch(evt.getKeyCode()) {
        case KeyEvent.VK_UP:
        case KeyEvent.VK_DOWN:
        case KeyEvent.VK_LEFT:
        case KeyEvent.VK_RIGHT:
            cueva.handleKey(evt);  
            break;

        case KeyEvent.VK_A:
            cueva.handleKey(evt);  
            break;

        case KeyEvent.VK_O:
            cueva.handleKey(evt); 
            break;

        case KeyEvent.VK_Q:
            exitGame(); 
            break;
    }

 
    repaint(); 
    }//GEN-LAST:event_formKeyPressed

    private void exitGame()
    {
        System.exit(0);
    }
    
    public void setCueva(Cueva cueva) {
        this.cueva= cueva;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); 
    
       cueva.draw(g);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
